extraction:
  python:  # Configure Python
    python_setup:  # Configure the setup
      version: 3  # Specify Version 3
      exclude_requirements: [pygromos/gromos/gromosPlsPls, pygromos/gromos/gromosXX]

path_classifiers:
  exclude:
    - pygromos/test
    - examples
    - setup.py
    - versioneer.py
