name: pygromos
channels:
  - conda-forge
  - defaults
dependencies:
  # Base depends
  - python
  - pip
  ## Compiling
  - gcc
  - openmpi
  - autoconf
  - automake
  ## Testing
  - pytest
  ## Meta
  - typing
  - pre-commit
  - jupyter
  - tqdm
  - ipywidgets
  - jupytext
  # Science
  - mpmath
  - pandas
  - pytables
  - numpy
  - sympy
  - scipy
  ## Chemie
  - openff-toolkit = 0.10.0
  - mdtraj
  - rdkit
  ## Visualization
  - matplotlib
  - nglview
