
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-04T16:20:08+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7f97e11a56df6201c579e007dd42549f08623201",
 "version": "v2.0+635.g7f97e11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
