
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-01T13:59:09+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5fbb77d85ddaaab4bf202b17a2a1e198e2c4fcab",
 "version": "v2.0+627.g5fbb77d"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
