
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-04T16:31:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "794b9623b025c908d752d2c58395921561d812d6",
 "version": "v2.0+636.g794b962"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
