name: pages-build-deployment #Build and Deploy
on:
  push:
    branches:
      - "main"
  dynamic:
    branches:
      - "main"

jobs:
  build:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a
      - uses: mamba-org/provision-with-micromamba@main
        with:
          python-version: ${{ matrix.python-version }}
          environment-file:  dev/conda_envs/test_env.yaml
          channels: conda-forge,defaults

          activate-environment: pygromosTest
          auto-update-conda: true
          auto-activate-base: false
          show-channel-urls: true

      - name: Install package

        # conda setup requires this special shell
        shell: bash -l {0}
        run: |
          python -m pip install . --no-deps
          conda list
      - name: build sphinx docs
        shell: bash -l {0}
        run: |
          python setup.py install
          cd docs/sphinx_project
          make clean;
          mkdir -p Examples Tutorials
          sphinx-apidoc -o _source ../../pygromos;
          cp ../../examples/ex*ipynb ./Examples;
          cp -r ../../examples/developer_examples ./Examples;
          cp ../../examples/t*ipynb ./Tutorials;
          python conf.py;
          make html;
          cp -rf _build/html/* ../
